### ISSUE TITLE
Just being curious.

### ISSUE THREAD

**Issue by lowryel** [Adesoji1/IbtLearning#1]
will it be an overdo if you implement any caching strategy?
This is great though.

**Comment by lowryel** [comment]
I've read the question now.

**Comment by Adesoji1** [comment]
I want to add helm chart configuration for deployment. Implementation of cache for the PHP server is greatly appreciated. Kindly provide the implementation sir @lowryel

**Comment by lowryel** [comment]
> I want to add helm chart configuration for deployment. Implementation of cache for the PHP server is greatly appreciated. Kindly provide the implementation sir @lowryel 

Okay. I'm doing that in the morning
